### PR TITLE
Attribute escaping optimization #961

### PR DESCRIPTION
**Pull request by sbmaxx**
Fixes "Attribute escaping optimization #961".

All tests are fine.

### CODE REVIEW

**Comment by narqo** [comment]
Could you rebase it after #981

**Comment by sbmaxx** [comment]
@narqo done

also, should i port https://github.com/bem/bem-core/issues/982 from `v3`?

**Comment by narqo** [comment]
> also, should i port #982 from v3?

~~@aristov already did it with #742~~
Oops, missread the original question. I think yes, we could port #742 to v2

**Comment by narqo** [comment]
:fire:

**Pull request merged**
