### PR TITLE
page: fix docs about `zoom` special field (close #1052)

### LINKED ISSUE #1052: page: fix docs about `zoom` special field

### PR DESCRIPTION
**Pull request by aristov**
Close #1052

### CODE REVIEW

**Comment by tadatuta** [comment]
shouldn't other html elems be updated for consistency?

**Comment by aristov** [comment]
What's wrong with other html elems?

**Comment by tadatuta** [comment]
they are ok but text is different:

> с атрибутом `name` – `'format-detection'`

VS

> `<meta>` с атрибутом `name` в значении `'viewport'`

**Comment by aristov** [comment]
@tadatuta done

**Comment by tadatuta** [comment]
lgtm

**Pull request merged**
