### PR TITLE
i-bem__dom: Rename containsDomElem() to containsEntity()

### LINKED ISSUE #1044: i-bem__dom: Rename containsDomElem() to containsBemEntity()

### PR DESCRIPTION
**Pull request by narqo**
closes #1044

/cc @dfilatov

### CODE REVIEW

**Comment by dfilatov** [comment]
I'm confused a little bit that you're using Bem Entity and BemDomEntity both for the same thing

**Comment by narqo** [comment]
Ok, I've rewrite the method's jsdoc. Now it's written [in the same way like we already have](https://github.com/bem/bem-core/blob/d7bd158c208dc8456d1e36981b2bbb6c3425d8a5/common.blocks/i-bem-dom/i-bem-dom.js#L212-L224) in i-bem-dom.js.

**Comment by narqo** [comment]
@dfilatov UP!

**Comment by dfilatov** [comment]
lgtm

**Pull request merged**
