### PR TITLE
Remove old junk

### PR DESCRIPTION
**Pull request by tadatuta**
1. Drop BEMHTML and BEMTREE base templates
2. Drop documentation for bem-xjst
3. Drop `i-bem__i18n`
4. Update `npm` dependencies and build scrips
5. Rename `*.bemhtml` to `*.bemhtml.js`

Closes (for `v3`):
- https://github.com/bem/bem-core/issues/1304
- https://github.com/bem/bem-core/issues/1283 
- https://github.com/bem/bem-core/issues/1258
- https://github.com/bem/bem-core/issues/984

### CODE REVIEW

**Comment by tadatuta** [comment]
cc @narqo @veged

**Comment by veged** [comment]
LGTM

**Comment by narqo** [comment]
Please backport it to v4 immediately. Nobody wants be repeat #1293

**Comment by tadatuta** [comment]
@narqo https://github.com/bem/bem-core/pull/1312

**Pull request merged**
