### PR TITLE
Fix bemtree nested promises problem

### PR DESCRIPTION
**Pull request by apsavin**
v3 part of #1079

### CODE REVIEW

**Comment by apsavin** [comment]
Please, don't merge it for a while, it seems that I did an error

**Comment by tadatuta** [comment]
@apsavin was `v2` branch also affected? should we postpone 2.7.0 release until you investigate the issue?

**Comment by apsavin** [comment]
No, the problem is only with this commit, because of difference between v2 and v3.

**Comment by aristov** [comment]
@apsavin say if you are ready for merge, please.

**Comment by apsavin** [comment]
@arikon sorry, I have no time for a while. And I don't want to fix this without tests. May be, it's better to close this PR?

**Comment by aristov** [comment]
Close in favour of #1107

**Pull request closed without merging**
