### PR TITLE
objects: extend fails in case of target=null (close #910)

### LINKED ISSUE #910: objects: extend fails in case of target=null

### PR DESCRIPTION
**Pull request by dfilatov**
cc @veged @narqo

### CODE REVIEW

**Comment by narqo** [comment]
Looks good. Let's fix method's JSDoc as well

**Comment by narqo** [comment]
Looks good. Let's fix method's JSDoc as well

**Comment by dfilatov** [comment]
fix what? `typeof null === 'object'`

**Comment by qfox** [comment]
:+1:

**Comment by narqo** [comment]
@dfilatov I think it's good to have at least something like this is JSDoc:

```
@param {Object} target object to extend or null
```

**Comment by dfilatov** [comment]
According to https://github.com/bem/bem-core/blob/issues/910%40v2/common.blocks/objects/objects.vanilla.js#L18 target can be anything, so I don't understand why `null` is the case which need to be described in jsdoc.

**Comment by qfox** [comment]
-1 for noticing `null` in jsdoc. It's an overkill since `typeof null === object`.

As compromise I suppose to use:

```
@param {?Object} target object
```

https://developers.google.com/closure/compiler/docs/js-for-compiler — Nullable type

**Comment by narqo** [comment]
@zxqfox at the same time they have explicit `null` in [@param example on the same page](https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-param)

Anyway, I don't insist. Let's merge than

**Comment by qfox** [comment]
@narqo okay ;-( But they have it in `{Type}`, not in description.

**Pull request merged**
