### PR TITLE
i-bem: introduce `this.reapply(context)`

### PR DESCRIPTION
**Pull request by indutny**
see https://github.com/bem/bem-xjst/issues/4

### CODE REVIEW

**Comment by narqo** [comment]
:+1: 

@veged ?

**Comment by veged** [comment]
I miss the point — why it calls REapply? Tme meaning of applying one more time is more suitable for applyNext ;-) Maybe applyNew or newApply?

**Comment by indutny** [comment]
I feel like `reapply` is a better naming for it, as it has almost nothing in common with `applyNext` and `applyCtx`. Because its outside of `xjst`'s subject, and basically the same as calling `exports.apply` whatever it is.

**Comment by narqo** [comment]
I like `reaplly` if anyone cares, but I think that we will get a lot of headache with all of this applies: `apply`, `applyNext`, `applyCtx`, `this.apply` and `this.reapply` for now. 'Cause no one cares where it came from, from xjst or plain-js or somewhere else.

**Comment by veged** [comment]
2 against 1 for `reapply` -- so I humble, let's merge it

@indutny can you rebase and merge?

**Comment by indutny** [comment]
Thanks, landed in 7584dfc.

**Pull request closed without merging**
