### PR TITLE
Update bem-xjst to 0.8.1, bemhtml-compat to 0.0.11

### PR DESCRIPTION
**Pull request by tadatuta**
// cc @veged @narqo

### CODE REVIEW

**Comment by narqo** [comment]
Some tests from `i-bem.test.bemhtml` and `i-bem__i18n.test.bemhtml` fail

**Comment by indutny** [comment]
@tadatuta I think I fixed it, sorry for a big delay!

**Comment by tadatuta** [comment]
@veged, tests for templates in `bem-components` pass with this branch. can we merge it?

**Comment by veged** [comment]
yep, I think so-- 
  Сергей Бережной

**Pull request merged**
