### PR TITLE
package: bump vow version

### LINKED ISSUE #837: vow: Bump version

### PR DESCRIPTION
**Pull request by qfox**
Fixes #837

### CODE REVIEW

**Comment by dfilatov** [comment]
@zxqfox Primarily, we're going to bump version here — https://github.com/bem/bem-core/blob/v2/common.blocks/vow/vow.vanilla.js. Could you do it as well?

**Comment by qfox** [comment]
@dfilatov Lol. sorry. Do we need commit with package.json?

**Comment by dfilatov** [comment]
@zxqfox I think we can include it as well

**Comment by dfilatov** [comment]
@zxqfox Thanks! Could you do the same PR to v3?

**Comment by qfox** [comment]
@dfilatov Yep, sure. #839

**Pull request merged**
