### PR TITLE
Attribute escaping optimization

### LINKED ISSUE #961: Attribute escaping optimization
У нас с незапамятных времен в базовых шаблонах BEMHTML функция attrEscape экранирует 4 символа: кавычку, амперсанд и треугольные скобки.
https://github.com/bem/bem-bl/blob/0.2/blocks-common/i-bem/__html/i-bem__html.bemhtml#L238
В bem-core так же: https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L229
А вот в BT экранируются только кавычка и амперсанд: https://github.com/enb-make/enb-bt/blob/master/lib/bt.js#L802
Я покурил интернетики на эту тему, поэкспериментировал в браузерах и пришел к выводу, что эскейпить треугольные скобки действительно не нужно (это касается только атрибутов).
В BH уже есть фикс: https://github.com/bem/bh/pull/137/files

Если оторвать эскейпинг треугольных скобок, это немного уменьшит время шаблонизации.

### PR DESCRIPTION
**Pull request by narqo**
/cc @veged @mishanga @sbmaxx 

Backport #979 into v3

closes #961

### CODE REVIEW

**Comment by sbmaxx** [comment]
Don't forget to remove escaping from `jsAttrEscape`:

``` js
BEMContext.prototype.jsAttrEscape = function attrEscape(str) {
    return (str + '').replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/'/g, '&#39;');
};
```

**Comment by narqo** [comment]
Crap, I've read the phrase from the original issue: "это касается только атрибутов" literally :) 

:up:

**Comment by sbmaxx** [comment]
:100:

**Comment by sbmaxx** [comment]
@narqo oh, one test failed ;(

**Comment by qfox** [comment]
attrEscape?

```
BEMContext.prototype.jsAttrEscape = function attrEscape(str) {
```

**Comment by narqo** [comment]
@zxqfox it's already fixed in the HEAD of v3

**Comment by qfox** [comment]
:+1: :smirk_cat:

**Comment by mishanga** [comment]
ок

**Pull request merged**
