### PR TITLE
v2 cherries @v3

### PR DESCRIPTION
**Pull request by qfox**
/cc @tadatuta

### CODE REVIEW

**Comment by veged** [comment]
HUGE work! awesome :+1: 

we just feel scare about changes in i-bem/i-bem-dom — maybe it's better to move these changes to separate PR so we can better review them

**Comment by qfox** [comment]
Well, okay, but give me a day plox ;-) I need to rest a little

**Comment by qfox** [comment]
@veged Впрочем... #844 I've moved out all `common.blocks/i-bem*` there except docs.

And also I've skipped some commits about `.enb/make`. Need @andrewblond or somebody here to fix that.

**Comment by qfox** [comment]
@tadatuta @veged ping.

**Comment by narqo** [comment]
@tadatuta could you add missed `desktop.blocks/page/page.tmpl-specs/40-css-ie.bemjson.js`

**Comment by aristov** [comment]
@tadatuta ping

**Pull request merged**
