### PR TITLE
i-bem: copypaste of actual documentation

### LINKED ISSUE #816: i-bem: make simlink to actual documentation

### PR DESCRIPTION
**Pull request by sipayRT**
Closes #816

### CODE REVIEW

**Comment by sipayRT** [comment]
@tadatuta @dfilatov

**Comment by tadatuta** [comment]
@tormozz48 Andrew, will it work fine?

**Comment by sipayRT** [comment]
this question not to @tormozz48 but to @andrewblond . @andrewblond can we gather documentation with simlinks by `enb-bem-docs`?

**Comment by tadatuta** [comment]
it's still to @tormozz48 because we don't need to have same page with different urls but to properly handle such situations consistently

**Comment by sipayRT** [comment]
@tadatuta I propose temporary to port documentation from common.docs level

**Pull request merged**
