### PR TITLE
Use jQuery 3.1

### LINKED ISSUE #1371: Use jQuery 3.1

### PR DESCRIPTION
**Pull request by tadatuta**
Closes #1371

### CODE REVIEW

**Review by narqo — CHANGES_REQUESTED** [review]
What about this code for old IEs https://github.com/bem/bem-core/blob/331d49c80a01157e1126b6bfad77a740eded8f78/desktop.blocks/jquery/__config/jquery__config.js#L16 

It looks like it'd break.

**Comment by tadatuta** [comment]
@narqo what exactly should break?

**Comment by narqo** [comment]
You've added changes:

``` diff
-                block1._domEvents(rootNode.find('div').andSelf()).un('dblclick');
+                block1._domEvents(rootNode.find('div').addBack()).un('dblclick');
```

Does jQuery 1.10 support this API?

**Comment by tadatuta** [comment]
I think it doesn't matter as it's in `spec.js` which we run only in phantom anyways.

**Pull request merged**
