### PR TITLE
Run linters for PR

### LINKED ISSUE #1043: Run linters for PR

### PR DESCRIPTION
**Pull request by tadatuta**
Closes #1043

### CODE REVIEW

**Comment by narqo** [comment]
@tadatuta looks like this PR is tad out of date, isn't it?

**Comment by qfox** [comment]
I've cherry-picked this into the current v3 here: #1239 
Guess, we can finish it there.

**Comment by narqo** [comment]
@zxqfox so we might close the PR? /cc @tadatuta

**Comment by qfox** [comment]
@narqo Yeah, I think so. Let's wait for @tadatuta's the last word!

**Comment by tadatuta** [comment]
Sure

**Pull request closed without merging**
