### PR TITLE
Impove bemtree error handling

### PR DESCRIPTION
**Pull request by apsavin**
...so you can do local error handling inside blocks and global inside process,  which calls BEMTREE.apply.
[Issue 594](https://github.com/bem/bem-core/issues/594)

### CODE REVIEW

**Comment by apsavin** [comment]
It's not so easy as it seems. May be, we should do something like this (it's a sketch).
And then use like this:

``` javascript
block('async-block').content()(function () {
    return this.addToQueue(
       this.wrapPromise(doRequestThatWillReturnAPromise())
             .then(function (data) {
                     //all is  ok
              },
              function (data) {
                     //we can do error handling here, if we want to handle the error in bemtree
                     //or we can do not provide this callback and then error handling must be done outside bemtree
               },
               this)
       );
});
```

By the way, is there any tests for bemtree?

**Comment by apsavin** [comment]
Guys, I think it's a serious problem and I don't know how to use BEMTREE in production without proper error handling.
Can you give me some feedback?

**Comment by apsavin** [comment]
@tadatuta?.. @narqo?.. Anybody?..

**Comment by tadatuta** [comment]
@apsavin I understand the reason of the first commit but I'm not sure if we really need to make things more complicated as in second one.

Isn't it enough to handle errors in BEMTREE like this:

``` js
block('b1').content()(function() {
    return this.doAsync(function() {
        var defer = Vow.defer(),
            promise = defer.promise();

        setTimeout(function() {
            defer.reject('упячка хеппенс');
        }, 10);

        return promise
            .fail(function(err) {
                return err; // will set the content of b1 to 'упячка хеппенс'
            });
    });
});
```

**Comment by apsavin** [comment]
I'm afraid, no.
See the example:

``` javascript
block('b1').content()(function() {
    return this.doAsync(function() {
        return doAsyncStuff().then(function (data) {
             return applyCtx({
                  block: 'b2', 
                  content: data,
                  b1Stuff: this.ctx.b1Stuff //will fail. We need to do applyAsync to have this.ctx here 
             }); 
        }, function (err) {return err;}, this);
    }, this);
});
```

``` javascript
block('b1').content()(function() {
    return this.doAsync(function() {
        return doAsyncStuff();
    }).then(function (data) {
             return applyCtx({
                  block: 'b2', 
                  content: data,
                  b1Stuff: this.ctx.b1Stuff 
             }); 
        }, function (err) {
            return err; //We will never be here because of changed error handling in doAsync
        }, this);;
});
```

Am I wrong?
I don't want to say that `wrapPromise` and `addToQueue` are good names for all that stuff, it's just a point to start a discussion.

**Comment by apsavin** [comment]
@tadatuta I created more simple variant [here](https://github.com/bem/bem-core/pull/601)

**Comment by apsavin** [comment]
Guys, can you give me a date, when you'll be able to pay attention to this problem?

**Comment by tadatuta** [comment]
@apsavin, it looks like BEMTREE needs to be totally reviewed as besides issue with error handling there's also another one with nested async calls: we need to do something like [this](https://github.com/bem/project-stub/commit/ada414d805d054571c7539539eebe6aa36146173#diff-f189455bb77673c7adc84822cf7a8919R11) in order to make them work now.

@veged, maybe we can schedule skype meeting together with @apsavin to find out what to do?

**Comment by veged** [comment]
we can do it at this week — pls arrange one of our "O2" meetigns for

(we also need @narqo to come)

**Comment by tadatuta** [comment]
@apsavin, as I can see in @veged's schedule it's possible to meet at 30.07 or 31.07 from 12:00 till 15:00 and 01.08 from 13:00 till 15:00. if it suits you, please, add me on skype (I'm `tadatuta` there) and tell which time is best.

**Comment by apsavin** [comment]
We decided to use another way #594

**Pull request closed without merging**
